### ISSUE TITLE
Does the code directly use “preprocessed features” that have been downloaded in advance?

### ISSUE THREAD

**Issue by Wind010321** [sosppxo/3D-STMN#10]
Hello,
    I have read your code but do not find the "preprocessed features" been used when training? 
    If I want to achieve this, should I change the code [here](https://github.com/sosppxo/3D-STMN/blob/b21fff26e7b7baa8694c3e0c7b148ea343dd5141/stmn/model/stmn_3d.py#L113C9-L115C83)? What I should do is to use the "ann_ids, scan_ids, object_id" to load the corresponding feature files? 
Thanks!

**Comment by Wind010321** [comment]
In other words, do you already have complete code for this operation?

**Comment by sosppxo** [comment]
We have two branch, and the preprocessed features is for the "feat" branch, as described in the beginning of the readme.

**Comment by Wind010321** [comment]
Thanks!
