### ISSUE TITLE
How to visualize results？

### ISSUE THREAD

**Issue by Li-Jinyuan** [sosppxo/3D-STMN#5]
Hello, how do you visualize the results? I found no relevant code.

**Comment by sosppxo** [comment]
Hello, visualizing code can be conveniently achieved using the Open3D library. However, we do not intend to organize and release it. In simple terms, you can save the predicted masks in https://github.com/sosppxo/3D-STMN/blob/b21fff26e7b7baa8694c3e0c7b148ea343dd5141/tools/test.py#L90 and then combine them with the ScanNet scene for visualization.
