### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by guoxinXiong** [sosppxo/3D-STMN#6]
Hello, Sir.

This work is interest.

Install segmentator from this [repo](https://github.com/Karbo123/segmentator) (We wrap the segmentator in ScanNet).
Install Stanford CoreNLP toolkit from the [official website](https://stanfordnlp.github.io/CoreNLP/download.html).

These two lines of instructions are difficult for me as a new learner in this field.
Can you provide more detailed instructions so that it's easy to follow?
Thank you very much.

**Comment by sosppxo** [comment]
For the [repo](https://github.com/Karbo123/segmentator), you can follow its **Build Example**. And for Stanford CoreNLP, you can just download the zip file and unzip it locally.
