### ISSUE TITLE
Is there any visualization method you folllowed?

### ISSUE THREAD

**Issue by Wind010321** [sosppxo/3D-STMN#7]
After inference, we can get some txt files. Is there method used to visualize the inference results you follow in the " "Acknowledgement" part ? I read these repos but find they use the ply file to visualize. Thanks!

**Comment by sosppxo** [comment]
There is a similar issue  #5 , and as you have the txt files  (i.e., predicted masks), you can read them and use the Open3D library to overlay them on the original scene with specific colors. Then, convert them to PLY files and visualize them. You can easily implement these using tools like ChatGPT.
