### ISSUE TITLE
If use visual data augmentation, there is any corresponding measures of the textual description in ScanRefer?

### ISSUE THREAD

**Issue by Wind010321** [sosppxo/3D-STMN#9]
I notice that the visual data augmentation is not applied. But you have given the visual data augmentation measures in the "data_aug" function. I want to know there is any code about the corresponding change code of the textual description if set the "aug==True"? Thanks!

**Comment by sosppxo** [comment]
The visual augmentation is not related to the textual description, so you can use it without modifying the code of text processing. But there is some mistake about sampling in it (so we do not use it in this repo), you can try to fix it, or wait for me to update the next version (but I do not have time for it in the short term).

**Comment by Wind010321** [comment]
OK，thanks for your replying!
